[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:envdump]
command=env
stdout_logfile=/tmp/envdump.log
autostart=false

[program:atlas-xcache]
command=/usr/local/sbin/runme_sv.sh
user=xrootd
autostart=true
autorestart=true
environment=LD_PRELOAD=/usr/lib64/libtcmalloc.so,TCMALLOC_RELEASE_RATE=10

