name: Build and Push ATLAS xcache images

on:
  push:
    branches:
      - "testing-upgrade"
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to OSG Harbor
        uses: docker/login-action@v4
        with:
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

      - name: Docker Build & Push XCACHE image
        uses: docker/build-push-action@v7
        with:
          context: atlas-xcache/.
          file: atlas-xcache/Dockerfile
          push: true
          tags: |
            ivukotic/atlas-xcache:05.26
            ivukotic/atlas-xcache:${{ github.sha }}
            hub.opensciencegrid.org/usatlas/atlas-xcache:05.26

      - name: Docker Build & Push HEARTBEATS image
        uses: docker/build-push-action@v7
        with:
          context: atlas-xcache/.
          file: atlas-xcache/Dockerfile.heartbeats
          push: true
          tags: |
            ivukotic/atlas-xcache-heartbeats:05.26
            ivukotic/atlas-xcache-heartbeats:${{ github.sha }}
            hub.opensciencegrid.org/usatlas/atlas-xcache-heartbeats:05.26

      - name: Show XRDCP version
        run: |
          docker run --rm ivukotic/atlas-xcache:05.26 xrdcp -version

      - name: Show Rucio client version
        run: |
          docker run --rm ivukotic/atlas-xcache-heartbeats:05.26 rucio --version
