name: Build XCache images from OSG Yum repositories
on:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  get-timestamp:
    name: Get timestamp for tagging images
    if: github.repository == 'opensciencegrid/docker-xcache'
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.timestamp-tag.outputs.dtag }}
    steps:
      - name: Get timestamp for timestamp tags
        id: timestamp-tag
        run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"
  base-image-build:
    name: Build initial xcache:fresh base image
    needs: get-timestamp
    runs-on: ubuntu-latest
    steps:
      - name: Check out docker-xcache
        uses: actions/checkout@v2
      - name: Build XCache base image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/xcache
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: ./xcache
          build_args: BASE_YUM_REPO=osg-upcoming-testing
          tags: upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}
  xcache-image-builds:
    name: Build ${{ matrix.image }}:fresh image
    strategy:
      matrix:
        image: [atlas-xcache, cms-xcache, stash-cache, stash-origin]
    needs:
      - get-timestamp
      - base-image-build
    runs-on: ubuntu-latest
    steps:
      - name: Check out docker-xcache
        uses: actions/checkout@v2
      - name: Replace FROM line in Dockerfile
        working-directory: ${{ matrix.image }}
        run: |
          sed -i \
            "s|FROM opensciencegrid/xcache:fresh|FROM docker.pkg.github.com/$GITHUB_REPOSITORY/xcache:upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}|" \
            Dockerfile
      - name: Build ${{ matrix.image }}:fresh image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/${{ matrix.image }}
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ matrix.image }}
          build_args: BASE_YUM_REPO=osg-upcoming-testing
          tags: upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}
  test-stash-cache:
    name: Test Stash Cache and Origin (fresh)
    needs:
      - get-timestamp
      - xcache-image-builds
    runs-on: ubuntu-latest
    steps:
      - name: Check out docker-xcache
        uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: ./tests/test_stashcache_origin.sh "docker.pkg.github.com/$GITHUB_REPOSITORY/stash-origin:upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}"
      - run: ./tests/test_stashcache.sh "docker.pkg.github.com/$GITHUB_REPOSITORY/stash-cache:upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}"
  push-images:
    name: Push ${{ matrix.image }}:fresh image
    if: contains(fromJson('["push", "repository_dispatch"]'), github.event_name) && github.repository == 'opensciencegrid/docker-xcache'
    strategy:
      matrix:
        image: [atlas-xcache, cms-xcache, stash-cache, stash-origin, xcache]
    needs:
      - get-timestamp
      - test-stash-cache
    runs-on: ubuntu-latest
    steps:
      - name: Check out docker-xcache
        uses: actions/checkout@v2
      - name: Create dummy Dockerfile
        run: echo "FROM docker.pkg.github.com/$GITHUB_REPOSITORY/${{ matrix.image }}:upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}" > Dockerfile
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/${{ matrix.image }}:upcoming-testing-${{ needs.get-timestamp.outputs.dtag }}
      - name: Build ${{ matrix.image}} image
        uses: docker/build-push-action@v1
        with:
          repository: opensciencegrid/${{ matrix.image }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: fresh, ${{ needs.get-timestamp.outputs.dtag }}
